# Generated by Django 4.0.4 on 2023-04-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='deliveries_payment',
            new_name='deliveries_payment_employee',
        ),
    ]
