# Generated by Django 4.0.4 on 2023-04-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
